apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: iban-api-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iban-service
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 90
